modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="videoplayer"
version="3.0.3"
displayName="VideoPlayer"
authors="Goedix"
description='''
This mod allows the playback of videos in the user interface (GUI), you can play videos for all connected users or for a specific user.
Thanks to anarkh_angel for the blocks.
'''
[[dependencies.videoplayer]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.videoplayer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.videoplayer]]
    modId="watermedia"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="CLIENT"
