modLoader="javafml"
loaderVersion="[41,)"
license="All Rights Reserved"
[[mods]]
modId="videoplayer"
version="3.0.5"
displayName="VideoPlayer"
authors="Goedix"
description='''
This mod allows the playback of videos in the user interface (GUI), you can play videos for all connected users or for a specific user.
Thanks to anarkh_angel for the blocks.
'''
credits="Thanks J-RAP for the help with the API"
[[dependencies.videoplayer]]
    modId="watermedia"
    mandatory=true
    versionRange="[2.0,)"
    ordering="AFTER"
    side="CLIENT"
